config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  get 'public/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "public#index"
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit Clone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <!-- Bootstrap CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/nav" %>

    <%= yield %>

    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_footer.html.erb
<p>Footer</p>

app/views/shared/_nav.html.erb
<nav>
  <img class="logo" src="https://logosmarcas.net/wp-content/uploads/2020/11/Reddit-Logo.png" alt="">
  <div class="search-bar">
    <form action="/">
      <span>
        <i class="fa-solid fa-magnifying-glass"></i>
        <input type="text" placeholder="Pesquisar no Reddit">
      </span>
    </form>
  </div>
  <div class="button-wrapper">
    <%= link_to "Login", new_account_session_path, class: "btn btn-outline-primary" %>
    <%= link_to "Sign Up", new_account_registration_path, class: "btn btn-primary" %>
  </div>
</nav>